### Get all categories
GET http://localhost:3000/api/categories
X-API-KEY: SECRETKEY
Accept: application/json

### Create new category
POST http://localhost:3000/api/categories
X-API-KEY: SECRETKEY
Accept: application/json
Content-Type: application/json

{
    "name": "testing"
}

### Get category by Id
GET http://localhost:3000/api/categories/5
X-API-KEY: SECRETKEY
Accept: application/json

### Update category by Id
PUT http://localhost:3000/api/categories/5
X-API-KEY: SECRETKEY
Accept: application/json
Content-Type: application/json

{
    "name": "iPod"
}

### Delete category by Id
DELETE http://localhost:3000/api/categories/3
X-API-KEY: SECRETKEY
Accept: application/json
